// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: model.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsModel_TodaysNews_FullMethodName = "/NewsModel/TodaysNews"
)

// NewsModelClient is the client API for NewsModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsModelClient interface {
	TodaysNews(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reciever], error)
}

type newsModelClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsModelClient(cc grpc.ClientConnInterface) NewsModelClient {
	return &newsModelClient{cc}
}

func (c *newsModelClient) TodaysNews(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reciever], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NewsModel_ServiceDesc.Streams[0], NewsModel_TodaysNews_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Reciever]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NewsModel_TodaysNewsClient = grpc.ServerStreamingClient[Reciever]

// NewsModelServer is the server API for NewsModel service.
// All implementations must embed UnimplementedNewsModelServer
// for forward compatibility.
type NewsModelServer interface {
	TodaysNews(*Request, grpc.ServerStreamingServer[Reciever]) error
	mustEmbedUnimplementedNewsModelServer()
}

// UnimplementedNewsModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsModelServer struct{}

func (UnimplementedNewsModelServer) TodaysNews(*Request, grpc.ServerStreamingServer[Reciever]) error {
	return status.Errorf(codes.Unimplemented, "method TodaysNews not implemented")
}
func (UnimplementedNewsModelServer) mustEmbedUnimplementedNewsModelServer() {}
func (UnimplementedNewsModelServer) testEmbeddedByValue()                   {}

// UnsafeNewsModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsModelServer will
// result in compilation errors.
type UnsafeNewsModelServer interface {
	mustEmbedUnimplementedNewsModelServer()
}

func RegisterNewsModelServer(s grpc.ServiceRegistrar, srv NewsModelServer) {
	// If the following call pancis, it indicates UnimplementedNewsModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsModel_ServiceDesc, srv)
}

func _NewsModel_TodaysNews_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NewsModelServer).TodaysNews(m, &grpc.GenericServerStream[Request, Reciever]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NewsModel_TodaysNewsServer = grpc.ServerStreamingServer[Reciever]

// NewsModel_ServiceDesc is the grpc.ServiceDesc for NewsModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NewsModel",
	HandlerType: (*NewsModelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TodaysNews",
			Handler:       _NewsModel_TodaysNews_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "model.proto",
}
